import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <header className="flex justify-between w-full py-2 px-2 bg-indigo-300">
          <div className="mainLink gap-2 text-xl text-white text-shadow-lg text-shadow-gray-500">
            <Link href={"/"}>홈페이지</Link>
          </div>

          <div className="subLink text-shadow-md text-shadow-gray-500 text-lime-100 space-x-2 ">
            <Link href={"/post"}>포스트</Link>
            <Link href={"/profile"}>프로파일</Link>
            <Link href={"/signup"}>회원가입</Link>
            <Link href={"/contact"}>문의하기</Link>

          </div>

        </header>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
